version: '3.6'
services:
  landing:
    build:
      context: "./"
      dockerfile: Dockerfile.dev
    networks:
      - ship
    environment:
      APP_ENV: development
    volumes:
      - "./src:/app/src"
    ports:
      - "3000:3000"
  db:
    container_name: db
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  pgdata: {}

networks:
  ship:
    name: ship_network